name: Magic-DiscordHelp
main: com.elmakers.mine.bukkit.plugins.help.MagicDiscordHelpPlugin
version: 1.0
api-version: 1.17
author: NathanWolf
description: A plugin to expose /mhelp to Discord
depend:
  - Magic

commands:
  evaluate:
    description: Run a parameterized weight evaluation
    permission: magic.commands.evaluate

permissions:
  magic.comamnds.evaluate:
    description: Run a weight evaluation
    type: boolean
    default: op
